"""GitHub API models for the agent pipeline.

This module defines the data models for GitHub API interactions, specifically
for pull request creation as part of the agent orchestration pipeline.

Requirements:
- 6.2: THE PR title SHALL include the original issue number and a summary
- 6.3: THE PR body SHALL include: approach summary, files changed, link to
       original issue

The models use Pydantic for validation, consistent with the pipeline's
approach in webhook/models.py and state/models.py.
"""

from datetime import datetime, timezone
from typing import Optional

from pydantic import BaseModel, Field, field_validator


class PRCreateRequest(BaseModel):
    """Request model for creating a GitHub pull request.

    This model contains all the information needed to create a pull request
    via the GitHub API. The PR links back to the original issue and includes
    an approach summary generated by the agent pipeline.

    Attributes:
        title: PR title including issue reference and brief summary.
               Format: "[#{issue_number}] {summary}"
        body: PR body with approach summary, files changed, and testing notes.
              Should include a link to the original issue using GitHub keywords.
        head_branch: The branch containing the changes to merge.
        base_branch: The target branch to merge into (usually 'main').
        labels: Labels to apply to the PR based on issue classification.
        reviewers: GitHub usernames to request as reviewers.
        issue_number: The original issue number this PR addresses.
        approach_summary: Summary of the implementation approach.
        files_changed: List of files modified in this PR.
        testing_notes: Notes about testing performed or required.
    """

    title: str = Field(
        ...,
        min_length=1,
        max_length=256,
        description="PR title including issue reference and brief summary",
    )

    body: str = Field(
        ...,
        description="PR body with approach summary, files changed, and testing notes",
    )

    head_branch: str = Field(
        ...,
        min_length=1,
        description="The branch containing the changes to merge",
    )

    base_branch: str = Field(
        default="main",
        min_length=1,
        description="The target branch to merge into",
    )

    labels: list[str] = Field(
        default_factory=list,
        description="Labels to apply to the PR based on issue classification",
    )

    reviewers: list[str] = Field(
        default_factory=list,
        description="GitHub usernames to request as reviewers",
    )

    issue_number: Optional[int] = Field(
        default=None,
        gt=0,
        description="The original issue number this PR addresses",
    )

    approach_summary: Optional[str] = Field(
        default=None,
        description="Summary of the implementation approach",
    )

    files_changed: list[str] = Field(
        default_factory=list,
        description="List of files modified in this PR",
    )

    testing_notes: Optional[str] = Field(
        default=None,
        description="Notes about testing performed or required",
    )

    @field_validator("title")
    @classmethod
    def title_not_empty_whitespace(cls, v: str) -> str:
        """Validate that title is not just whitespace."""
        if not v.strip():
            raise ValueError("Title cannot be empty or whitespace only")
        return v

    @field_validator("head_branch", "base_branch")
    @classmethod
    def branch_not_empty_whitespace(cls, v: str) -> str:
        """Validate that branch names are not just whitespace."""
        if not v.strip():
            raise ValueError("Branch name cannot be empty or whitespace only")
        return v

    def format_body(self) -> str:
        """Generate a formatted PR body from the component fields.

        This method creates a well-structured PR body that includes:
        - Link to the original issue (using GitHub keywords for auto-linking)
        - Approach summary describing the implementation
        - List of files changed
        - Testing notes

        Returns:
            str: Formatted PR body in GitHub-flavored markdown.
        """
        sections = []

        if self.issue_number:
            sections.append(f"Closes #{self.issue_number}\n")

        if self.approach_summary:
            sections.append("## Approach Summary\n")
            sections.append(f"{self.approach_summary}\n")

        if self.files_changed:
            sections.append("## Files Changed\n")
            for file_path in self.files_changed:
                sections.append(f"- `{file_path}`")
            sections.append("")

        if self.testing_notes:
            sections.append("## Testing Notes\n")
            sections.append(f"{self.testing_notes}\n")

        return "\n".join(sections) if sections else self.body

    @classmethod
    def create_for_issue(
        cls,
        issue_number: int,
        summary: str,
        head_branch: str,
        approach_summary: str,
        files_changed: list[str],
        testing_notes: Optional[str] = None,
        base_branch: str = "main",
        labels: Optional[list[str]] = None,
        reviewers: Optional[list[str]] = None,
    ) -> "PRCreateRequest":
        """Factory method to create a PR request for an issue.

        This method creates a properly formatted PR request with the title
        and body structured according to the pipeline requirements.

        Args:
            issue_number: The original issue number this PR addresses.
            summary: Brief summary of the changes for the PR title.
            head_branch: The branch containing the changes.
            approach_summary: Description of the implementation approach.
            files_changed: List of files modified in this PR.
            testing_notes: Optional notes about testing.
            base_branch: Target branch to merge into (default: 'main').
            labels: Optional labels to apply to the PR.
            reviewers: Optional reviewers to request.

        Returns:
            PRCreateRequest: A fully configured PR creation request.
        """
        title = f"[#{issue_number}] {summary}"

        request = cls(
            title=title,
            body="",  # Will be generated by format_body
            head_branch=head_branch,
            base_branch=base_branch,
            labels=labels or [],
            reviewers=reviewers or [],
            issue_number=issue_number,
            approach_summary=approach_summary,
            files_changed=files_changed,
            testing_notes=testing_notes,
        )

        request.body = request.format_body()
        return request


class PRCreateResult(BaseModel):
    """Result model for a successfully created pull request.

    This model contains the information returned by GitHub after
    successfully creating a pull request.

    Attributes:
        pr_number: The pull request number assigned by GitHub.
        pr_url: The full URL to the pull request on GitHub.
        created_at: Timestamp when the PR was created.
        html_url: Alias for pr_url for GitHub API compatibility.
        head_sha: The SHA of the head commit (optional).
        state: The PR state (usually 'open' for newly created PRs).
    """

    pr_number: int = Field(
        ...,
        gt=0,
        description="The pull request number assigned by GitHub",
    )

    pr_url: str = Field(
        ...,
        min_length=1,
        description="The full URL to the pull request on GitHub",
    )

    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Timestamp when the PR was created (UTC)",
    )

    html_url: Optional[str] = Field(
        default=None,
        description="Alias for pr_url for GitHub API compatibility",
    )

    head_sha: Optional[str] = Field(
        default=None,
        description="The SHA of the head commit",
    )

    state: str = Field(
        default="open",
        description="The PR state (usually 'open' for newly created PRs)",
    )

    def model_post_init(self, __context) -> None:
        """Set html_url from pr_url if not provided."""
        if self.html_url is None:
            object.__setattr__(self, "html_url", self.pr_url)

    @classmethod
    def from_github_response(cls, response: dict) -> "PRCreateResult":
        """Create a PRCreateResult from a GitHub API response.

        This factory method parses the GitHub API response for PR creation
        and extracts the relevant fields.

        Args:
            response: The JSON response from GitHub's create PR endpoint.

        Returns:
            PRCreateResult: Parsed result with PR details.

        Raises:
            KeyError: If required fields are missing from the response.
            ValueError: If the response data is invalid.
        """
        created_at_str = response.get("created_at")
        created_at = (
            datetime.fromisoformat(created_at_str.replace("Z", "+00:00"))
            if created_at_str
            else datetime.now(timezone.utc)
        )

        return cls(
            pr_number=response["number"],
            pr_url=response["html_url"],
            created_at=created_at,
            html_url=response.get("html_url"),
            head_sha=response.get("head", {}).get("sha"),
            state=response.get("state", "open"),
        )
