"""PR creation logic for the agent pipeline.

Orchestrates pull request creation after successful Kiro CLI execution.
Builds a PR with issue linkage, approach summary, classification-based
labels, reviewer requests, and a comment on the original issue.

Requirements:
- 6.1: Create a PR in the target repository when kiro-cli succeeds
- 6.2: PR title includes original issue number and summary
- 6.3: PR body includes approach summary, files changed, issue link
- 6.4: Link PR to original issue using GitHub keywords
- 6.5: Add labels based on issue classification
- 6.6: Request reviewers based on CODEOWNERS or configuration
- 6.7: Comment on original issue with link to created PR

Source:
- src/pipeline/github/client.py (GitHubClient)
- src/pipeline/github/models.py (PRCreateRequest, PRCreateResult)
- src/pipeline/classifier/models.py (IssueClassification, IssueType)
- src/pipeline/runner/kiro.py (KiroResult)
"""

import logging
from dataclasses import dataclass
from typing import Optional

from src.pipeline.classifier.models import IssueClassification, IssueType
from src.pipeline.github.client import GitHubClient
from src.pipeline.github.models import PRCreateRequest, PRCreateResult
from src.pipeline.runner.kiro import KiroResult

logger = logging.getLogger(__name__)

ISSUE_TYPE_LABEL_MAP: dict[IssueType, str] = {
    IssueType.FEATURE: "enhancement",
    IssueType.BUG: "bug",
    IssueType.DOCUMENTATION: "documentation",
    IssueType.INFRASTRUCTURE: "infrastructure",
}


@dataclass
class PRCreationResult:
    """Outcome of the full PR creation workflow.

    Attributes:
        pr_number: Pull request number assigned by GitHub.
        pr_url: Full URL to the pull request.
        comment_posted: Whether the issue comment was posted successfully.
    """

    pr_number: int
    pr_url: str
    comment_posted: bool


def map_issue_type_to_label(issue_type: IssueType) -> Optional[str]:
    """Map an IssueType to a GitHub label name.

    Args:
        issue_type: The classified issue type.

    Returns:
        Label name string, or None for UNKNOWN types.
    """
    return ISSUE_TYPE_LABEL_MAP.get(issue_type)


def build_pr_title(issue_number: int, issue_title: str) -> str:
    """Build a PR title referencing the original issue.

    Format: "Fix #<number>: <title>"

    Args:
        issue_number: The original issue number.
        issue_title: The original issue title.

    Returns:
        Formatted PR title string.
    """
    return f"Fix #{issue_number}: {issue_title}"


def build_pr_body(
    issue_number: int,
    approach_summary: str,
    classification: IssueClassification,
    files_changed: list[str],
) -> str:
    """Build a PR body with issue link, approach summary, and metadata.

    The body uses the "Closes #N" keyword to auto-link the PR to the
    issue when merged.

    Args:
        issue_number: The original issue number.
        approach_summary: Summary extracted from Kiro CLI output.
        classification: The issue classification result.
        files_changed: List of file paths changed by the implementation.

    Returns:
        Formatted PR body in GitHub-flavored markdown.
    """
    sections: list[str] = []

    sections.append(f"Closes #{issue_number}\n")

    sections.append("## Approach Summary\n")
    sections.append(f"{approach_summary}\n")

    if files_changed:
        sections.append("## Files Changed\n")
        for file_path in files_changed:
            sections.append(f"- `{file_path}`")
        sections.append("")

    sections.append("## Classification\n")
    sections.append(f"- **Type:** {classification.issue_type.value}")
    if classification.affected_packages:
        packages = ", ".join(classification.affected_packages)
        sections.append(f"- **Affected packages:** {packages}")
    sections.append("")

    return "\n".join(sections)


def build_issue_comment(pr_number: int, pr_url: str) -> str:
    """Build a comment to post on the original issue.

    Args:
        pr_number: The created PR number.
        pr_url: The full URL to the created PR.

    Returns:
        Markdown comment body.
    """
    return (
        f"🤖 **Automated PR created:** [#{pr_number}]({pr_url})\n\n"
        "This pull request was generated by the Archon agent pipeline."
    )


def build_labels(classification: IssueClassification) -> list[str]:
    """Build the label list for a PR based on classification.

    Always includes "archon-automated". Adds a classification-specific
    label when the issue type maps to a known label.

    Args:
        classification: The issue classification result.

    Returns:
        List of label name strings.
    """
    labels = ["archon-automated"]
    type_label = map_issue_type_to_label(classification.issue_type)
    if type_label is not None:
        labels.append(type_label)
    return labels


def extract_approach_summary(kiro_result: KiroResult) -> str:
    """Extract an approach summary from Kiro CLI output.

    Uses the first 2000 characters of stdout as the approach summary.
    Falls back to a default message when stdout is empty.

    Args:
        kiro_result: The result from Kiro CLI execution.

    Returns:
        Approach summary string.
    """
    stdout = kiro_result.stdout.strip()
    if not stdout:
        return "Implementation completed by Archon agent pipeline."
    if len(stdout) > 2000:
        return stdout[:2000] + "\n\n_(output truncated)_"
    return stdout


class PRCreator:
    """Orchestrates PR creation after successful Kiro CLI execution.

    Coordinates building the PR request, creating the PR via the GitHub
    API, and posting a comment on the original issue.

    Attributes:
        github_client: Authenticated GitHub API client.
    """

    def __init__(self, github_client: GitHubClient):
        self.github_client = github_client

    async def create_pr_for_issue(
        self,
        owner: str,
        repo: str,
        issue_number: int,
        issue_title: str,
        head_branch: str,
        kiro_result: KiroResult,
        classification: IssueClassification,
        reviewers: Optional[list[str]] = None,
        base_branch: str = "main",
        files_changed: Optional[list[str]] = None,
    ) -> PRCreationResult:
        """Create a PR and comment on the original issue.

        Args:
            owner: Repository owner.
            repo: Repository name.
            issue_number: Original issue number.
            issue_title: Original issue title.
            head_branch: Branch with the implementation changes.
            kiro_result: Result from Kiro CLI execution.
            classification: Issue classification result.
            reviewers: GitHub usernames to request as reviewers.
            base_branch: Target branch to merge into.
            files_changed: List of files modified.

        Returns:
            PRCreationResult with PR number, URL, and comment status.
        """
        approach_summary = extract_approach_summary(kiro_result)
        title = build_pr_title(issue_number, issue_title)
        body = build_pr_body(
            issue_number,
            approach_summary,
            classification,
            files_changed or [],
        )
        labels = build_labels(classification)

        pr_request = PRCreateRequest(
            title=title,
            body=body,
            head_branch=head_branch,
            base_branch=base_branch,
            labels=labels,
            reviewers=reviewers or [],
            issue_number=issue_number,
            approach_summary=approach_summary,
            files_changed=files_changed or [],
        )

        logger.info(
            "Creating PR for issue",
            extra={
                "owner": owner,
                "repo": repo,
                "issue_number": issue_number,
                "head_branch": head_branch,
                "labels": labels,
            },
        )

        pr_result = await self.github_client.create_pr(owner, repo, pr_request)

        comment_posted = await self._post_issue_comment(
            owner, repo, issue_number, pr_result.pr_number, pr_result.pr_url
        )

        return PRCreationResult(
            pr_number=pr_result.pr_number,
            pr_url=pr_result.pr_url,
            comment_posted=comment_posted,
        )

    async def _post_issue_comment(
        self,
        owner: str,
        repo: str,
        issue_number: int,
        pr_number: int,
        pr_url: str,
    ) -> bool:
        """Post a comment on the original issue linking to the PR.

        Returns True on success, False if the comment fails (non-fatal).

        Args:
            owner: Repository owner.
            repo: Repository name.
            issue_number: Issue to comment on.
            pr_number: Created PR number.
            pr_url: Created PR URL.

        Returns:
            True if comment was posted, False otherwise.
        """
        comment_body = build_issue_comment(pr_number, pr_url)
        try:
            await self.github_client.create_comment(
                owner, repo, issue_number, comment_body
            )
            logger.info(
                "Posted PR link comment on issue",
                extra={
                    "owner": owner,
                    "repo": repo,
                    "issue_number": issue_number,
                    "pr_number": pr_number,
                },
            )
            return True
        except Exception:
            logger.exception(
                "Failed to post comment on issue",
                extra={
                    "owner": owner,
                    "repo": repo,
                    "issue_number": issue_number,
                    "pr_number": pr_number,
                },
            )
            return False
