apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: deploy-knowledge-base
  namespace: archon-agent
  labels:
    app: archon-agent
    component: deployment
spec:
  description: >-
    This pipeline deploys the Archon knowledge base by creating an ArgoCD Application
    that watches the ArchonAgent repository. ArgoCD handles the actual deployment
    and keeps the cluster in sync with Git.

  params:
    - name: git-url
      type: string
      description: Git repository URL containing the manifests
      default: https://github.com/bdchatham/ArchonAgent
    - name: git-revision
      type: string
      description: Git revision (branch, tag, or commit SHA)
      default: main
    - name: manifest-path
      type: string
      description: Path within the repository containing Kubernetes manifests
      default: manifests/knowledge-base
    - name: app-name
      type: string
      description: Name of the ArgoCD Application
      default: archon-knowledge-base
    - name: target-namespace
      type: string
      description: Target namespace where the application will be deployed
      default: archon-kb

  tasks:
    - name: deploy-to-argocd
      taskRef:
        name: argocd-deployment
      params:
        - name: app-name
          value: $(params.app-name)
        - name: repo-url
          value: $(params.git-url)
        - name: repo-revision
          value: $(params.git-revision)
        - name: manifest-path
          value: $(params.manifest-path)
        - name: target-namespace
          value: $(params.target-namespace)
        - name: auto-sync
          value: "true"
        - name: prune
          value: "true"
        - name: self-heal
          value: "true"
        - name: create-namespace
          value: "true"

