apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: archon-pipeline
spec:
  params:
    - name: git-url
      type: string
      description: Git repository URL
    - name: git-revision
      type: string
      description: Git revision to build
      default: main
  workspaces:
    - name: source
      description: Source code workspace
  tasks:
    - name: clone-repo
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: tekton-pipelines
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: source
    
    - name: run-tests
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: python-test
          - name: namespace
            value: tekton-pipelines
      runAfter:
        - clone-repo
      params:
        - name: test-command
          value: "pytest --cov=archon --cov-report=term"
      workspaces:
        - name: source
          workspace: source
